urls.py
from django.urls import path

from . import views

app_name = "whitebox"

urlpatterns = [
    #AUTH stuff
    path('get_username', views.get_username),
    path('register', views.register, name='register'),
    path('signin', views.signin, name='signin'),
    path('LogoutPage', views.LogoutPage, name='LogoutPage'),
    
    #CharacterList and Character stuff
    path('character_generate/<str:name>/', views.character_generate),
    path('CharacterList', views.CharacterListView.as_view()),
    path('MyCharacterList', views.MyCharacterListView.as_view()),
    #supports GET, DELETE, and PUT
    path('characters/<int:pk>/', views.character_detail),
    
    #MeleeWeaponList and MeleeWeapon stuff
    path('MeleeWeaponList', views.MeleeWeaponListView.as_view()),
    #POST used for buying
    path('MeleeWeaponTransaction', views.MeleeWeaponTransaction),
    
    #RangedWeaponList and RangedWeapon stuff
    path('RangedWeaponList', views.RangedWeaponListView.as_view()),
    #POST used for buying
    path('RangedWeaponTransaction', views.RangedWeaponTransaction),
    
    #MeleeWeapon stuff
    
    #single page application URLs
    path('vue_test', views.vue_test),
    path('', views.vue_test)
]

models.py
from django.db import models
from django.contrib.auth.models import User
import random

def roll_attribute():
    a = 0
    for x in range(3):
        a += random.randrange(1,6)
    return a

def roll_starting_cash():
    a = 0
    for x in range(3):
        a += random.randrange(1, 6) * 10
    return a
        
class MeleeWeapon(models.Model):
    name = models.CharField(max_length=40)
    damage = models.CharField(max_length=40)
    weight = models.IntegerField()
    cost_gp = models.IntegerField()

    def __str__(self):
        r = self.name + " / " + self.damage + " / " + str(self.weight) + " / " + str(self.cost_gp) + " gp "
        return r

# USAGE: To add melee weapons to a character,
# MeleeWeaponQuantity.objects.create(character=character, melee_weapon=melee_weapon, quantity =quantity)
class MeleeWeaponQuantity(models.Model):
    character = models.ForeignKey('Character', related_name = 'melee_weapon_quantity', on_delete = models.SET_NULL, null = True)
    melee_weapon = models.ForeignKey('MeleeWeapon', related_name = 'melee_weapon_quantity', on_delete = models.SET_NULL, null = True, blank = True)
    quantity = models.IntegerField(default=1)
    
    def __str__(self):
        return str(self.character.name) + " " + str(self.character.id) + " / " + str(self.melee_weapon.name)
        
class RangedWeapon(models.Model):
    name = models.CharField(max_length=40)
    damage = models.CharField(max_length=40)
    weight = models.IntegerField()
    rof = models.FloatField()
    w_range = models.IntegerField()
    cost_gp = models.IntegerField()

    def __str__(self):
        r = self.name + " / " + self.damage + " / " + str(self.rof) + " / " + str(self.w_range) + " / "  + str(self.weight) + " / " +  str(self.cost_gp) + " gp "
        return r

# USAGE: To add ranged weapons to a character,
# RangedWeaponQuantity.objects.create(character=character, melee_weapon=melee_weapon, quantity =quantity)        
class RangedWeaponQuantity(models.Model):
    character = models.ForeignKey('Character', related_name = 'raned_weapon_quantity', on_delete = models.SET_NULL, null = True)
    ranged_weapon = models.ForeignKey('RangedWeapon', related_name = 'ranged_weapon_quantity', on_delete = models.SET_NULL, null = True, blank = True)
    quantity = models.IntegerField(default=1)

class Character(models.Model):
    FIGHTER = 0
    MAGE = 1
    THIEF = 2
    CLERIC = 3
    name = models.CharField(max_length=40, default = "Scrub")
    strength = models.IntegerField(default=3)
    dexterity = models.IntegerField(default=3)
    constitution = models.IntegerField(default=3)
    intelligence = models.IntegerField(default=3)
    wisdom = models.IntegerField(default=3)
    charisma = models.IntegerField(default=3)
    gold = models.IntegerField(default=30)
    silver = models.IntegerField(default=0)
    copper = models.IntegerField(default=0)
    c_role = models.IntegerField(null=True)
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    finalized = models.BooleanField(default=False)
    melee_weapons = models.ManyToManyField('MeleeWeapon', through='MeleeWeaponQuantity', related_name='melee_weapons')
    ranged_weapons = models.ManyToManyField('RangedWeapon', through='RangedWeaponQuantity', related_name='ranged_weapons')

    def get_username(self):
        if (self.user):
            return self.user.username
        return ''

    def get_role(self):
        if (self.c_role is not None):
            if (self.c_role == 0):
                return "Fighter"
            if (self.c_role == 1):
                return "Mage"
            if (self.c_role == 2):
                return "Thief"
            if (self.c_role == 3):
                return "Cleric"
            else:
                return "Person"
        else:
            return "Person"
    def roll(self, name):
        self.name = name
        self.strength = roll_attribute()
        self.dexterity = roll_attribute()
        self.constitution = roll_attribute()
        self.intelligence = roll_attribute()
        self.wisdom = roll_attribute()
        self.charisma = roll_attribute()
        self.gold = roll_starting_cash()
        self.silver = 0
        self.copper = 0
        return self
        
    def __str__(self):
        r = self.name + ": STR " + str(self.strength) + " / "
        r += "DEX " + str(self.dexterity) + " / "
        r += "CON " + str(self.constitution) + " / "
        r += "INT " + str(self.intelligence) + " / "
        r += "WIS " + str(self.wisdom) + " / "
        r += "CHA " + str(self.charisma) + " / "
        r += "GOLD " + str(self.gold) + " / "
        r += "SILVER " + str(self.silver) + " / "
        r += "COPPER " + str(self.copper) + " / "
        if (self.user == None):
            r += "Created by anonymous"
        else:
            r += "Created by " + self.user.username
        if self.finalized:
            r += " / Character has been finalized."
        else:
            r += " / Character not yet finalized."
        return r
        
    def purchase_melee_weapon(self, melee_weapon):
        if (self.gold >= melee_weapon.cost_gp):
            self.gold -= melee_weapon.cost_gp
            melee_weapon_quantity = MeleeWeaponQuantity.objects.create(character=self, melee_weapon=melee_weapon, quantity = 1)
            self.save()
            
    def purchase_ranged_weapon(self, ranged_weapon):
        if (self.gold >= ranged_weapon.cost_gp):
            self.gold -= ranged_weapon.cost_gp
            ranged_weapon_quantity = RangedWeaponQuantity.objects.create(character=self, ranged_weapon=ranged_weapon, quantity = 1)
            self.save()
        
    # used to see if dumping points into core role stat is legal
    # if dump is legal, performs dump. Character will still need to be saved.
    # s d c i w c = strength dexterity constitution intelligence wisdom charisma
    # return 0 or an error message detailing why the dump is not legal
    def finalize(self, c_role, s, d, co, i, w, ch):

        if self.finalized:
            return "Character has already been finalized."

        dump_from = "Cannot dump ? so that it is below 9. "
        dump_to = "Cannot dump ? so that it is above 18."
        total_dump = s + d + co + i + w + ch
        r = ""
        if (self.strength - s < 9 and s > 0):
            r += dump_from.replace("?","strength")
        if (self.dexterity - d < 9 and d > 0):
            r += dump_from.replace("?","dexterity")
        if (self.constitution - co < 9 and co > 0):
            r += dump_from.replace("?","constitution")
        if (self.intelligence - i < 9 and i > 0) :
            r += dump_from.replace("?","intelligence")
        if (self.wisdom - w < 9 and w > 0):
            r += dump_from.replace("?","wisdom")
        if (self.charisma - ch < 9 and ch > 0):
            r += dump_from.replace("?","charisma")

        if (int(c_role) == self.FIGHTER):
            if total_dump + self.strength - s > 18:
                r += dump_to.replace("?", "strength")
            else:
                self.strength += total_dump - s
        elif (int(c_role) == self.MAGE):
            if total_dump + self.intelligence - i > 18:
                r += dump_to.replace("?", "intelligence")
            else:
                self.intelligence += total_dump - i
        elif (int(c_role) == self.THIEF):
            if total_dump + self.dexterity + d > 18:
                r += dump_to.replace("?", "dexterity")
            else:
                self.dexterity += total_dump - d
        elif (int(c_role) == self.CLERIC):
            if total_dump + self.wisdom + w > 18:
                r += dump_to.replace("?", "wisdom")
            else:
                self.wisdom += total_dump - w
        else:
            r += "Invalid character role " + c_role + " selected."

        if (len(r) == 0):
            self.strength -= s
            self.dexterity -= d
            self.constitution -= co
            self.intelligence -= i
            self.wisdom -= w
            self.charisma -= ch
            self.c_role = c_role
            self.finalized = True
            return 0
        else:
            return r

templates/whitebox/FinalizeForm.html
{% extends "whitebox/base_template.html" %}

{% block content %}

{% if request.user.is_authenticated %}
<h1>Finalize {{ character.name }}</h1>
You can dump points from your other stats into your most important stat based on your chosen class. Your most important stat cannot exceed 18 and you cannot dump a stat so that it goes below 9.
<div id="app">
<form action="{% url 'whitebox:finalize' character.id %}" method="post">
    {% csrf_token %}
<table>
    <tr><td>Character Role:</td><td colspan="2">
        <select v-model="c_role" name="c_role">
            <option value={{ character.FIGHTER }}>Fighter (Strength)</option>
            <option value={{ character.MAGE }}>Mage (Intelligence)</option>
            <option value={{ character.THIEF }}>Thief (Dexterity)</option>
            <option value={{ character.CLERIC }}>Cleric (Wisdom)</option>
        </select></td>
    </tr>
    <tr><td>Strength:</td><td align="right"><% strength.original %></td><td><label>Dump</label> <input v-model="strength.dump" type="number" name="s" value="0" min="0" v-on:click="dumpCheck"></td><td><% strength.message %></td></tr>
    <tr><td>Dexterity:</td><td align="right"><% dexterity.original %></td><td><label>Dump</label> <input v-model="dexterity.dump" type="number" name="d" value="0" min="0" v-on:click="dumpCheck"></td><td><% dexterity.message %></td></tr>
    <tr><td>Constitution:</td><td align="right"><% constitution.original %></td><td><label>Dump</label> <input v-model="constitution.dump" type="number" name="co" value="0" min="0" v-on:click="dumpCheck"></td><td><% constitution.message %></td></tr>
    <tr><td>Intelligence:</td><td align="right"><% intelligence.original %></td><td><label>Dump</label> <input v-model="intelligence.dump" type="number" name="i" value="0" min="0" v-on:click="dumpCheck"></td><td><% intelligence.message %></td></tr>
    <tr><td>Wisdom:</td><td align="right"><% wisdom.original %></td><td><label>Dump</label> <input v-model="wisdom.dump" type="number" name="w" value="0" min="0" v-on:click="dumpCheck"></td><td><% wisdom.message %></td></tr>
    <tr><td>Charisma:</td><td align="right"><% charisma.original %></td><td><label>Dump</label> <input v-model="charisma.dump" type="number" name="ch" value="0"  min="0" v-on:click="dumpCheck"></td><td><% charisma.message %></td></tr>
</table>
    <input type="submit" value="Finalize">
</form>
</div>

<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script>
      var app = new Vue({
        el: '#app',
        delimiters: ['<%', '%>'],
        data: {
            strength: {
                original : {{ character.strength }},
                dump : 0,
                message : "Final Value: {{ character.strength }}"
            },
            dexterity : {
                original: {{ character.dexterity }},
                dump : 0,
                message : "Final Value: {{ character.dexterity }}"
            },
            constitution : {
                original : {{ character.constitution }},
                dump : 0,
                message : "Final Value: {{ character.constitution }}"
            },
            intelligence : {
                original : {{ character.intelligence }},
                dump : 0,
                message : "Final Value: {{ character.intelligence }}"
            },
            wisdom : {
                original : {{ character.wisdom }},
                dump : 0,
                message : "Final Value: {{ character.wisdom }}"
            },
            charisma : {
                original : {{ character.charisma }},
                dump : 0,
                message : "Final Value: {{ character.charisma }}"
            },
            dumpTotal : 0,
            c_role : {{ character.FIGHTER }}
        },
        methods: {
            dumpCheck: function (event) {
                if (this.strength.dump > 0 && this.strength.original - this.strength.dump < 9) { this.strength.message = "You cannot dump a stat so that its value goes below 9."; }
                else {this.strength.message = "Final Value: " + (this.strength.original - this.strength.dump);}

                if (this.dexterity.dump > 0 && this.dexterity.original - this.dexterity.dump < 9) { this.dexterity.message = "You cannot dump a stat so that its value goes below 9."; }
                else {this.dexterity.message = "Final Value: " + (this.dexterity.original - this.dexterity.dump);}

                if (this.constitution.dump > 0 && this.constitution.original - this.constitution.dump < 9) { this.constitution.message = "You cannot dump a stat so that its value goes below 9."; }
                else {this.constitution.message = "Final Value: " + (this.constitution.original - this.constitution.dump);}

                if (this.intelligence.dump > 0 && this.intelligence.original - this.intelligence.dump < 9) { this.intelligence.message = "You cannot dump a stat so that its value goes below 9."; }
                else {this.intelligence.message = "Final Value: " + (this.intelligence.original - this.intelligence.dump);}

                if (this.wisdom.dump>0 && this.wisdom.original - this.wisdom.dump < 9) { this.wisdom.message = "You cannot dump a stat so that its value goes below 9."; }
                else {this.wisdom.message = "Final Value: " + (this.wisdom.original - this.wisdom.dump);}
                if (this.charisma.dump>0 && this.charisma.original - this.charisma.dump < 9) { this.charisma.message = "You cannot dump a stat so that its value goes below 9."; }
                else {this.charisma.message = "Final Value: " + (this.charisma.original - this.charisma.dump);}

                this.dumpTotal = Number(this.strength.dump) + Number(this.dexterity.dump) + Number(this.constitution.dump) + Number(this.intelligence.dump) + Number(this.wisdom.dump) + Number(this.charisma.dump);

                if (this.c_role == {{ character.FIGHTER }}) {
                            if (Number(this.strength.original) + this.dumpTotal > 18) { this.strength.message = "You cannot pump a stat above 18."; }
                            else (this.strength.message = "Final Value: " + (Number(this.strength.original) + this.dumpTotal - Number(this.strength.dump)))
                        }

                if (this.c_role == {{ character.MAGE }}) {
                    if (Number(this.intelligence.original) + this.dumpTotal > 18) { this.intelligence.message = "You cannot pump a stat above 18."; }
                    else (this.intelligence.message = "Final Value: " + (Number(this.intelligence.original) + this.dumpTotal - Number(this.intelligence.dump)))
                }

                if (this.c_role == {{ character.THIEF }}) {
                    if (Number(this.dexterity.original) + this.dumpTotal > 18) { this.dexterity.message = "You cannot pump a stat above 18."; }
                    else (this.dexterity.message = "Final Value: " + (Number(this.dexterity.original) + this.dumpTotal - Number(this.dexterity.dump)))
                }

                if (this.c_role == {{ character.CLERIC }}) {
                    if (Number(this.wisdom.original) + this.dumpTotal > 18) { this.wisdom.message = "You cannot pump a stat above 18."; }
                    else (this.wisdom.message = "Final Value: " + (Number(this.wisdom.original) + this.dumpTotal - Number(this.wisdom.dump)))
                }

                return;
            }
        }
      })
</script>

{% endif %}

{% if not request.user.is_authenticated and not character.finalized %}
You must be logged in and own the character in question in order to finalize.
{% endif %}

{% if request.user.is_authenticated and character.finalized %}
Character is already finalized.
{% endif %}

{% endblock %}

templates/whitebox/ViewAll.html
{% extends "whitebox/base_template.html" %}

{% block content %}

{% if character_list %}
<table><tr><td align="left">
    Characters:
    <ul>
    {% for character in character_list %}
        <li><a href="/whitebox/{{ character.id }}/ViewDetail">{{ character.name }} the {{ character.get_role }}</a></li>
    {% endfor %}
    </ul>
</td></tr></table>
{% else %}
    <p>No characters are available.</p>
{% endif %}

{% endblock %}

templates/whitebox/ViewDetail.html
{% extends "whitebox/base_template.html" %}

{% block content %}

<h1>{{ character.name }} the  {{ character.get_role }}</h1>
<table>
    <tr><td>Strength:</td><td align="right">{{ character.strength }}</td></tr>
    <tr><td>Dexterity:</td><td align="right">{{ character.dexterity }}</td></tr>
    <tr><td>Constitution:</td><td align="right">{{ character.constitution }}</td></tr>
    <tr><td>Intelligence:</td><td align="right">{{ character.intelligence }}</td></tr>
    <tr><td>Wisdom:</td><td align="right">{{ character.wisdom }}</td></tr>
    <tr><td>Charisma:</td><td align="right">{{ character.charisma }}</td></tr>
    <tr><td>Gold:</td><td align="right">{{ character.gold }}</td></tr>
    <tr><td>Silver:</td><td align="right">{{ character.silver }}</td></tr>
    <tr><td>Copper:</td><td align="right">{{ character.copper }}</td></tr>
</table>

{% if request.user.is_authenticated and not character.finalized and request.user == character.user %}
<p><a href="/whitebox/{{ character.id }}/FinalizeForm">Finalize Character</a></p>
{% endif %}

{% if request.user.is_authenticated and request.user == character.user %}
<p><a href="/whitebox/{{ character.id }}/delete">Delete Character</a></p>
{% endif %}

{% endblock %}

templates/whitebox/base_template.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <link rel="stylesheet" href="{% static 'whitebox/style.css' %}">
    <title>{% block title %}Whitebox{% endblock %}</title>
</head>

<body>
    <div id="sidebar" align="center">
        <h1>Whitebox Character Manager</h1>
        {% block sidebar %}
         <table><tr><td align="left">
        <ul>
            {% if request.user.is_authenticated %}
                <li><a href="/whitebox/ViewAll">Character List</a></li>
                <li><a href="/whitebox/ViewMine">View My Characters Only</a></li>
                <li><a href="/whitebox/GenerateForm">Generate Another Character</a></li>
                <li><a href="/whitebox/LogoutPage">Logout {{ request.user.username }}</a></li>
            {% endif %}

            {% if not request.user.is_authenticated %}
                <li><a href="/whitebox/ViewAll">Character List</a></li>
                <li><a href="/whitebox/GenerateForm">Generate Another Character</a></li>
                <li><a href="/whitebox/LoginForm">User Login</a></li>
                <li><a href="/whitebox/RegisterForm">Register User</a></li>
            {% endif %}
        </ul>
        </td></tr></table>
        {% endblock %}
    </div>

    <div id="content" align="center">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

templates/whitebox/generate.html
{% extends "whitebox/base_template.html" %}

{% block content %}

<h1>Generate Character</h1>
<form action="{% url 'whitebox:generate' %}" method="post">
{% csrf_token %}
<fieldset>
        <label>Name</label> <input type="text" name="name" value="Scrub">
</fieldset>
<input type="submit" value="Generate">
</form>

{% endblock %}

templates/whitebox/index.html
{% extends "whitebox/base_template.html" %}

{% block content %}

{% endblock %}

templates/whitebox/login.html
{% extends "whitebox/base_template.html" %}

{% block content %}

<h1>User Login</h1>
<form action="{% url 'whitebox:signin' %}" method="post">
{% csrf_token %}
<fieldset>
        <p><label>Username</label> <input type="text" name="username" value="Username"></p>
        <p><label>Password</label> <input type="password" name="password" value="password"></p>
</fieldset>
<input type="submit" value="Login">
</form>

{% endblock %}

templates/whitebox/register.html
{% extends "whitebox/base_template.html" %}

{% block content %}

<h1>Register User</h1>
<form action="{% url 'whitebox:register' %}" method="post">
{% csrf_token %}
<fieldset>
        <table>
                <tr><td><label>Username</label></td><td><input type="text" name="username" value="Username"></td></tr>
        <tr><td><label>Email</label> </td><td><input type="text" name="email" value="email@address.com"></td></tr>
        <tr><td><label>Password</label></td><td> <input type="password" name="password" value="password"></td></tr>
        </table>
</fieldset>
<input type="submit" value="Register User">
</form>

{% endblock %}

templates/whitebox/vue_test.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
    <link rel="stylesheet" href="{% static 'whitebox/style.css' %}">
    <title>{% block title %}Whitebox{% endblock %}</title>
</head>
    <body>
    {% csrf_token %}
    <center><h1>Whitebox Character Manager</h1></center>
        <div id="app"></div>
        <script type="text/javascript" src="{% static 'src/vue/dist/js/chunk-vendors.js' %}"></script>
        <script type="text/javascript" src="{% static 'src/vue/dist/js/app.js' %}"></script>
        <link href="{% static 'src/vue/dist/css/app.css' %}" rel=stylesheet>
    </body>
</html>